//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect2ObjectWCF
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MetadataDTO", Namespace = "http://schemas.datacontract.org/2004/07/Proiect2ObjectWCF", IsReference = true)]
    public partial class MetadataDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime CreatedAtField;

        private string FIleTypeField;

        private Proiect2ObjectWCF.FileDTO FileField;

        private int FileIDField;

        private int IdField;

        private bool IsDeletedField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIleType
        {
            get
            {
                return this.FIleTypeField;
            }
            set
            {
                this.FIleTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect2ObjectWCF.FileDTO File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileID
        {
            get
            {
                return this.FileIDField;
            }
            set
            {
                this.FileIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FileDTO", Namespace = "http://schemas.datacontract.org/2004/07/Proiect2ObjectWCF", IsReference = true)]
    public partial class FileDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string FilePathField;

        private int IdField;

        private Proiect2ObjectWCF.MetadataDTO MetadataField;

        private Proiect2ObjectWCF.PropertyDTO[] PropertiesField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect2ObjectWCF.MetadataDTO Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect2ObjectWCF.PropertyDTO[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PropertyDTO", Namespace = "http://schemas.datacontract.org/2004/07/Proiect2ObjectWCF", IsReference = true)]
    public partial class PropertyDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string EventNameField;

        private Proiect2ObjectWCF.FileDTO FileField;

        private int FileId1Field;

        private int IdField;

        private string LandscapeNameField;

        private string PersonNameField;

        private string PlaceNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventName
        {
            get
            {
                return this.EventNameField;
            }
            set
            {
                this.EventNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Proiect2ObjectWCF.FileDTO File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId1
        {
            get
            {
                return this.FileId1Field;
            }
            set
            {
                this.FileId1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LandscapeName
        {
            get
            {
                return this.LandscapeNameField;
            }
            set
            {
                this.LandscapeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName
        {
            get
            {
                return this.PersonNameField;
            }
            set
            {
                this.PersonNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceName
        {
            get
            {
                return this.PlaceNameField;
            }
            set
            {
                this.PlaceNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IFileMetadataProperty")]
public interface IFileMetadataProperty
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMetadata/GetAllMedata", ReplyAction = "http://tempuri.org/IMetadata/GetAllMedataResponse")]
    Proiect2ObjectWCF.MetadataDTO[] GetAllMedata();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMetadata/GetAllMedata", ReplyAction = "http://tempuri.org/IMetadata/GetAllMedataResponse")]
    System.Threading.Tasks.Task<Proiect2ObjectWCF.MetadataDTO[]> GetAllMedataAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/SaveFile", ReplyAction = "http://tempuri.org/IFile/SaveFileResponse")]
    void SaveFile(Proiect2ObjectWCF.FileDTO file);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/SaveFile", ReplyAction = "http://tempuri.org/IFile/SaveFileResponse")]
    System.Threading.Tasks.Task SaveFileAsync(Proiect2ObjectWCF.FileDTO file);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/GetAllFiles", ReplyAction = "http://tempuri.org/IFile/GetAllFilesResponse")]
    Proiect2ObjectWCF.FileDTO[] GetAllFiles();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/GetAllFiles", ReplyAction = "http://tempuri.org/IFile/GetAllFilesResponse")]
    System.Threading.Tasks.Task<Proiect2ObjectWCF.FileDTO[]> GetAllFilesAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/FileFilter", ReplyAction = "http://tempuri.org/IFile/FileFilterResponse")]
    Proiect2ObjectWCF.FileDTO[] FileFilter(string condition);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/FileFilter", ReplyAction = "http://tempuri.org/IFile/FileFilterResponse")]
    System.Threading.Tasks.Task<Proiect2ObjectWCF.FileDTO[]> FileFilterAsync(string condition);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/DeleteFile", ReplyAction = "http://tempuri.org/IFile/DeleteFileResponse")]
    void DeleteFile(Proiect2ObjectWCF.FileDTO file);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFile/DeleteFile", ReplyAction = "http://tempuri.org/IFile/DeleteFileResponse")]
    System.Threading.Tasks.Task DeleteFileAsync(Proiect2ObjectWCF.FileDTO file);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProperties/GetAllProperties", ReplyAction = "http://tempuri.org/IProperties/GetAllPropertiesResponse")]
    Proiect2ObjectWCF.PropertyDTO[] GetAllProperties();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProperties/GetAllProperties", ReplyAction = "http://tempuri.org/IProperties/GetAllPropertiesResponse")]
    System.Threading.Tasks.Task<Proiect2ObjectWCF.PropertyDTO[]> GetAllPropertiesAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProperties/AddProperty", ReplyAction = "http://tempuri.org/IProperties/AddPropertyResponse")]
    void AddProperty(Proiect2ObjectWCF.PropertyDTO property);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IProperties/AddProperty", ReplyAction = "http://tempuri.org/IProperties/AddPropertyResponse")]
    System.Threading.Tasks.Task AddPropertyAsync(Proiect2ObjectWCF.PropertyDTO property);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFileMetadataPropertyChannel : IFileMetadataProperty, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FileMetadataPropertyClient : System.ServiceModel.ClientBase<IFileMetadataProperty>, IFileMetadataProperty
{

    public FileMetadataPropertyClient()
    {
    }

    public FileMetadataPropertyClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public FileMetadataPropertyClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public FileMetadataPropertyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public FileMetadataPropertyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public Proiect2ObjectWCF.MetadataDTO[] GetAllMedata()
    {
        return base.Channel.GetAllMedata();
    }

    public System.Threading.Tasks.Task<Proiect2ObjectWCF.MetadataDTO[]> GetAllMedataAsync()
    {
        return base.Channel.GetAllMedataAsync();
    }

    public void SaveFile(Proiect2ObjectWCF.FileDTO file)
    {
        base.Channel.SaveFile(file);
    }

    public System.Threading.Tasks.Task SaveFileAsync(Proiect2ObjectWCF.FileDTO file)
    {
        return base.Channel.SaveFileAsync(file);
    }

    public Proiect2ObjectWCF.FileDTO[] GetAllFiles()
    {
        return base.Channel.GetAllFiles();
    }

    public System.Threading.Tasks.Task<Proiect2ObjectWCF.FileDTO[]> GetAllFilesAsync()
    {
        return base.Channel.GetAllFilesAsync();
    }

    public Proiect2ObjectWCF.FileDTO[] FileFilter(string condition)
    {
        return base.Channel.FileFilter(condition);
    }

    public System.Threading.Tasks.Task<Proiect2ObjectWCF.FileDTO[]> FileFilterAsync(string condition)
    {
        return base.Channel.FileFilterAsync(condition);
    }

    public void DeleteFile(Proiect2ObjectWCF.FileDTO file)
    {
        base.Channel.DeleteFile(file);
    }

    public System.Threading.Tasks.Task DeleteFileAsync(Proiect2ObjectWCF.FileDTO file)
    {
        return base.Channel.DeleteFileAsync(file);
    }

    public Proiect2ObjectWCF.PropertyDTO[] GetAllProperties()
    {
        return base.Channel.GetAllProperties();
    }

    public System.Threading.Tasks.Task<Proiect2ObjectWCF.PropertyDTO[]> GetAllPropertiesAsync()
    {
        return base.Channel.GetAllPropertiesAsync();
    }

    public void AddProperty(Proiect2ObjectWCF.PropertyDTO property)
    {
        base.Channel.AddProperty(property);
    }

    public System.Threading.Tasks.Task AddPropertyAsync(Proiect2ObjectWCF.PropertyDTO property)
    {
        return base.Channel.AddPropertyAsync(property);
    }
}
