//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proiect1
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;

    [DataContract(IsReference = true)]
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.Properties = new HashSet<Property>();
            this.Metadata = new Metadata();
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string FilePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Property> Properties { get; set; }
        [DataMember]
        public virtual Metadata Metadata { get; set; }
    }
}
